Repository kodeklubben/oppgaver, pull requests merged in 2018-08, with the labels that each got.

#856 Processing: Verden del 1 på nynorsk
  src/processing/verden_del1/verden_del1_nn.md
Labels: PR: Needs Review

#855 Processing: Trigonometri på nynorsk
  src/processing/trigonometri/trigonometri_nn.md
Labels: PR: Needs Review

#854 Processing: To player på nynorsk
  src/processing/to_player/to_player_nn.md
Labels: PR: Needs Review

#750 Scratch: Snøballkrig på nynorsk
  src/scratch/snoballkrig/snoballkrig.md
  src/scratch/snoballkrig/snoballkrig_nn.md
Labels: PR: Needs Review

#857 Processing: Verden del 2 på nynorsk
  src/processing/verden_del2/verden_del2_nn.md
Labels: PR: Needs Review

#862 Microbit: Hermegåsa på nynorsk
  src/microbit/pxt_hermegaasa/hermegaasa_nn.md
Labels: PR: Needs Review

#531 Processing - nytt spill: bildepresentasjon
  src/processing/1_Bildepresentasjon/Bildepresetasjon.md
  src/processing/1_Bildepresentasjon/fjerdedelsjo.png
  src/processing/1_Bildepresentasjon/halvsjo.png
  src/processing/1_Bildepresentasjon/midtensjo.png
  src/processing/1_Bildepresentasjon/midtensjo2.png
  src/processing/1_Bildepresentasjon/preview.png
  src/processing/1_Bildepresentasjon/sjoogspace1.png
  src/processing/1_Bildepresentasjon/sjoogspace2.png
  src/processing/1_Bildepresentasjon/sjoogspace3.png
  src/processing/1_Bildepresentasjon/space.jpg
  src/processing/1_Bildepresentasjon/steg1.png
  src/processing/1_Bildepresentasjon/steg2.png
  src/processing/1_Bildepresentasjon/steg3.png
  src/processing/1_Bildepresentasjon/steg4.png
  src/processing/1_Bildepresentasjon/steg5.png
  src/processing/1_Bildepresentasjon/steg6.png
  src/processing/1_Bildepresentasjon/steg6ekstra.png
  src/processing/1_Bildepresentasjon/trekant.png
  src/processing/1_Bildepresentasjon/undersea.jpg
Labels: PR: Needs Review

#884 Processing: bildepresentasjon - Fiksa filnamn, fjerna unøvendige filer
  src/processing/1_Bildepresentasjon/steg1.png
  src/processing/1_Bildepresentasjon/steg2.png
  src/processing/1_Bildepresentasjon/steg3.png
  src/processing/1_Bildepresentasjon/steg4.png
  src/processing/1_Bildepresentasjon/steg5.png
  src/processing/1_Bildepresentasjon/steg6.png
  src/processing/1_Bildepresentasjon/steg6ekstra.png
  src/processing/bildepresentasjon/bildepresentasjon.md
  src/processing/bildepresentasjon/fjerdedelsjo.png
  src/processing/bildepresentasjon/halvsjo.png
  src/processing/bildepresentasjon/midtensjo.png
  src/processing/bildepresentasjon/midtensjo2.png
  src/processing/bildepresentasjon/preview.png
  src/processing/bildepresentasjon/sjoogspace1.png
  src/processing/bildepresentasjon/sjoogspace2.png
  src/processing/bildepresentasjon/sjoogspace3.png
  src/processing/bildepresentasjon/space.jpg
  src/processing/bildepresentasjon/trekant.png
  src/processing/bildepresentasjon/undersea.jpg
Labels: PR: Needs Review

#885 Processing: Uendelig bakke - LV
  src/processing/uendelig_bakke/README.md
Labels: PR: Needs Review

#886 Processing: Bildepresentasjon - LV
  src/processing/bildepresentasjon/README.md
Labels: PR: Needs Review

#887 Microbit: Buttons på nynorsk
  src/microbit/python_buttons/python_buttons_nn.md
Labels: PR: Needs Review

#876 Elm - Sorted yaml, removed level, fixed indents, trailing whitespace etc
  src/elm/01_prov_i_nettleser/01_prov_i_nettleser.md
  src/elm/02_funksjoner_elm_repl/02_funksjoner_elm_repl.md
  src/elm/03_moduler_elm_reactor/03_moduler_elm_reactor.md
  src/elm/04_input/04_input.md
  src/elm/05_tegne/05_tegne.md
  src/elm/06_lare_andres_spill/06_lare_andres_spill.md
  src/elm/07_tell_sekunder/07_tell_sekunder.md
  src/elm/08_mus/08_mus.md
  src/elm/09_egen_kode/09_egen_kode.md
  src/elm/10_fraktaler/10_fraktaler.md
  src/elm/11_prosjekt/11_prosjekt.md
  src/elm/index.md
  src/elm/index_nn.md
Labels: on hold

#934 Python: Installasjon av PGZero
  src/python/hangman2/hangman2.md
  src/python/hangman2/hangman2_nn.md
  src/python/lopende_strekmann/lopende_strekmann.md
  src/python/lopende_strekmann/lopende_strekmann_nn.md
  src/python/sprettball/sprettball.md
  src/python/sprettball/sprettball_nn.md
Labels: PR: Needs Review

#933 Nytt tips til klassikar-oppgåvene
  src/scratch/asteroids/README.md
  src/scratch/breakout/README.md
  src/scratch/donkey_kong/README.md
  src/scratch/lunar_lander/README.md
  src/scratch/pong/README.md
  src/scratch/snake/README.md
Labels: PR: Needs Review

#920 Scratch: Pong - LV nynorsk
  src/scratch/pong/README_nn.md
Labels: PR: Needs Review

#919 Scratch: Pingviner på tur - LV nynorsk
  src/scratch/pingviner_pa_tur/README_nn.md
Labels: PR: Needs Review

#916 Scratch: Lunar Lander - LV nynorsk
  src/scratch/lunar_lander/README_nn.md
Labels: PR: Needs Review

#915 Scratch: Lag ditt eget spill - LV nynorsk
  src/scratch/lag_ditt_eget_spill/README_nn.md
Labels: PR: Needs Review

#914 Scratch: Labyrint - LV nynorsk
  src/scratch/labyrint/README_nn.md
Labels: PR: Needs Review

#912 Scratch: King Kong - LV nynorsk
  src/scratch/kingkong/README_nn.md
Labels: PR: Needs Review

#908 Scratch: Hva er det? - LV nynorsk
  src/scratch/hva_er_det/README_nn.md
Labels: PR: Needs Review

#907 Scratch: Hoppehelt - LV nynorsk
  src/scratch/hoppehelt/README_nn.md
Labels: PR: Needs Review

#898 Scratch: Bruke data - LV nynorsk
  src/scratch/data_navn/README_nn.md
Labels: PR: Needs Review

#897 Scratch: Bursdag i Antarktis - LV nynorsk
  src/scratch/bursdag_i_antarktis/README_nn.md
Labels: PR: Needs Review

#896 Scratch: Breakout - LV nynorsk
  src/scratch/breakout/README_nn.md
Labels: PR: Needs Review

#895 Scratch: Astrokatt - LV nynorsk
  src/scratch/astrokatt/README_nn.md
Labels: PR: Needs Review

#893 Scratch: Asteroids - LV nynorsk
  src/scratch/asteroids/README_nn.md
Labels: PR: Needs Review

#909 Scratch: Hvor i all verden? - LV nynorsk
  src/scratch/hvor_i_all_verden_del1/README.md
  src/scratch/hvor_i_all_verden_del1/README_nn.md
  src/scratch/hvor_i_all_verden_del1/hvor_i_all_verden_del1.md
  src/scratch/hvor_i_all_verden_del1/hvor_i_all_verden_del1_nn.md
  src/scratch/hvor_i_all_verden_del2/README.md
  src/scratch/hvor_i_all_verden_del2/README_nn.md
  src/scratch/hvor_i_all_verden_del2/hvor_i_all_verden_del2.md
  src/scratch/hvor_i_all_verden_del2/hvor_i_all_verden_del2_nn.md
  src/scratch/hvor_i_all_verden_del3/README.md
  src/scratch/hvor_i_all_verden_del3/README_nn.md
  src/scratch/hvor_i_all_verden_del3/hvor_i_all_verden_del3.md
  src/scratch/hvor_i_all_verden_del3/hvor_i_all_verden_del3_nn.md
Labels: PR: Reviewed w/ Comments

#879 Computercraft - Sorted yaml, removed level, fixed indents, trailing whitespace etc
  src/computercraft/README.md
  src/computercraft/bli_kjent_med_datamaskinen/bli_kjent_med_datamaskinen.md
  src/computercraft/bygg_et_hus/bygg_et_hus.md
  src/computercraft/fjernstyr_en_robot/fjernstyr_en_robot.md
  src/computercraft/hendelser/hendelser.md
  src/computercraft/index.md
  src/computercraft/index_en.md
  src/computercraft/installasjon/installasjon.md
  src/computercraft/introduksjon_til_computercraft/introduksjon_til_computercraft.md
  src/computercraft/nettverk_send_beskjed/nettverk_send_beskjed.md
  src/computercraft/robotinvasjon/robotinvasjon.md
  src/computercraft/sprettball/sprettball.md
Labels: on hold

#878 Arduino - Sorted yaml, removed level, fixed indents, trailing whitespace etc
  src/arduino/7_segment_display/7_segment_display.md
  src/arduino/7_segment_display/README.md
  src/arduino/blinkende_lysdiode/README.md
  src/arduino/blinkende_lysdiode/blinkende_lysdiode.md
  src/arduino/buzzer/README.md
  src/arduino/buzzer/buzzer.md
  src/arduino/index.md
  src/arduino/rgb_diode/README.md
  src/arduino/rgb_diode/rgb_diode.md
  src/arduino/ultralydsensor/README.md
  src/arduino/ultralydsensor/ultralydsensor.md
Labels: on hold

#877 Processing - Sorted yaml, removed level, fixed indents, trailing whitespace etc
  src/processing/README.md
  src/processing/ekstern_processing_org/hello_processing.md
  src/processing/farger/README.md
  src/processing/farger/farger.md
  src/processing/farger/farger_nn.md
  src/processing/index.md
  src/processing/index_en.md
  src/processing/index_nn.md
  src/processing/interaktiv_intro/introduksjon.md
  src/processing/mangekanter/README.md
  src/processing/mangekanter/mangekanter.md
  src/processing/mangekanter/mangekanter_nn.md
  src/processing/pingpong/README.md
  src/processing/pingpong/pingpong.md
  src/processing/pingpong/pingpong_nn.md
  src/processing/sprettende_ball/README.md
  src/processing/sprettende_ball/sprettende_ball.md
  src/processing/sprettende_ball/sprettende_ball_nn.md
  src/processing/tegnespillet/README.md
  src/processing/tegnespillet/tegnespillet.md
  src/processing/tegnespillet/tegnespillet_nn.md
  src/processing/tetris/README.md
  src/processing/tetris/tetris.md
  src/processing/tetris/tetris_nn.md
  src/processing/to_player/README.md
  src/processing/to_player/to_player.md
  src/processing/to_player/to_player_nn.md
  src/processing/trigonometri/README.md
  src/processing/trigonometri/trigonometri.md
  src/processing/trigonometri/trigonometri_nn.md
  src/processing/verden_del1/README.md
  src/processing/verden_del1/verden_del1.md
  src/processing/verden_del1/verden_del1_nn.md
  src/processing/verden_del2/README.md
  src/processing/verden_del2/verden_del2.md
  src/processing/verden_del2/verden_del2_nn.md
Labels: on hold
