Repository kodeklubben/oppgaver, pull requests merged in 2019-08, with the labels that each got.

#1146 Soloball -> Scratch 3
  src/scratch/soloball/soloball.md
Labels: on hold

#1143 Snake -> Scratch 3
  src/scratch/snake/snake.md
Labels: on hold

#984 Scratch 2->3 spill lyden -> start lyden
  src/scratch/bursdag_i_antarktis/bursdag_i_antarktis.md
  src/scratch/bursdag_i_antarktis/bursdag_i_antarktis_nn.md
  src/scratch/felix_og_herbert/felix_og_herbert.md
  src/scratch/flaksefugl/flaksefugl.md
  src/scratch/flaksefugl/flaksefugl_nn.md
  src/scratch/fyrverkeri/fyrverkeri.md
  src/scratch/fyrverkeri/fyrverkeri_nn.md
  src/scratch/jafsefisk/jafsefisk.md
  src/scratch/jafsefisk/jafsefisk_nn.md
  src/scratch/kingkong/kingkong.md
  src/scratch/norgestur/norgestur.md
  src/scratch/norgestur/norgestur_nn.md
  src/scratch/orkenlop/orkenlop.md
  src/scratch/orkenlop/orkenlop_nn.md
  src/scratch/spokelsesjakten/spokelsesjakten.md
  src/scratch/spokelsesjakten/spokelsesjakten_nn.md
  src/scratch/tegneprogram/tegneprogram.md
Labels: on hold

#1178 Fix tags
  src/microbit/pxt_lagegetbilde/lesson.yml
  src/microbit/pxt_trykkforbilde/lesson.yml
Labels: PR: Needs Review

#978 Filtertags på islandsk
  filtertags/keys.yml
  filtertags/translation_da.yml
  filtertags/translation_en.yml
  filtertags/translation_is.yml
  filtertags/translation_nb.yml
  filtertags/translation_nn.yml
  filtertags/translation_sv.yml
Labels: on hold, work-in-progress
