Repository kodeklubben/oppgaver, pull requests merged in 2019-09, with the labels that each got.

#1205 Fix microbitbugs
  src/microbit/pxt_komponer_en_melodi/andre_linje.png
  src/microbit/pxt_komponer_en_melodi/tredje_linje.png
  src/microbit/pxt_komponer_en_melodi/velg_tone.png
  src/microbit/pxt_send_en_hemmelig_beskjed/hemmelig_beskjed.png
  src/microbit/pxt_send_en_hemmelig_beskjed/naar_radio_mottar.png
  src/microbit/pxt_send_en_hemmelig_beskjed/send_en_hemmelig_beskjed.md
  src/microbit/pxt_send_en_hemmelig_beskjed/vis_mottat_beskjed.png
  src/microbit/pxt_snake/snake.md
  src/microbit/pxt_snake/snake_nn.md
Labels: PR: Needs Review

#1206 Felix og Herbert på islandsk
  src/scratch/felix_og_herbert/felix_og_herbert_is.md
Labels: Ready to merge

#1165 Nytt micro:bit pxt prosjekt
  src/microbit/pxt_ildfluer/ensom_flue.png
  src/microbit/pxt_ildfluer/ildfluer.md
  src/microbit/pxt_ildfluer/lesson.yml
  src/microbit/pxt_ildfluer/radiomottak.png
  src/microbit/pxt_ildfluer/sosial_flue.png
  src/microbit/pxt_ildfluer/start.png
Labels: PR: Reviewed w/ Comments
